name: DynamicFormBuilder CI/CD

on:
  push:
    branches:
      - main

  workflow_dispatch:


jobs:

  test:

    name: Test Application

    runs-on: self-hosted

    steps:

    - name: Checkout Code
      uses: actions/checkout@v4


    - name: Check Project Structure
      run: |
        pwd
        find . -name "*.csproj"


    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'


    - name: Restore Packages
      run: |
        cd DynamicFormBuilder/DynamicFormBuilder
        dotnet restore


    - name: Build Application
      run: |
        cd DynamicFormBuilder/DynamicFormBuilder
        dotnet build --configuration Release --no-restore

    - name: Run Unit Test
  
      run: |
  
        dotnet test DynamicFormBuilder.Tests/DynamicFormBuilder.Tests.csproj \
        --configuration Release \
        --logger "trx;LogFileName=test-result.trx" \
        --results-directory ./TestResults


    - name: Upload Test Result Artifact
      uses: actions/upload-artifact@v4
      with:
        name: dynamicformbuilder-test-result
        path: DynamicFormBuilder/DynamicFormBuilder/TestResults

  deploy:

    name: Deploy Application

    needs: test

    runs-on: self-hosted


    steps:
    - name: Download Test Result
      uses: actions/download-artifact@v4
      with:
        name: dynamicformbuilder-test-result
        path: /home/ubuntu/test
        
    - name: Checkout Code
      uses: actions/checkout@v4


    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'


    - name: Publish Application
      run: |
        cd DynamicFormBuilder/DynamicFormBuilder
        dotnet publish \
        --configuration Release \
        --output /var/www/dynamicformbuilder


    - name: Restart Application
      run: |
        sudo systemctl restart dynamicbuilder.service


    - name: Verify Application
      run: |
        sudo systemctl status dynamicbuilder.service --no-pager
